### ISSUE TITLE
DAC-Filter-Capacitor causes large temp-co

### ISSUE THREAD

**Issue by pathfinder49** [OxfordIonTrapGroup/stabilizer_current_sense#10]
C33 is causing ~50 mV fluctuations in V_err. 
![67689050-ac229600-f992-11e9-9db8-70882b72895f](https://user-images.githubusercontent.com/14295481/67709503-f8cb9880-f9b5-11e9-931b-671637d2ba76.png)
This measurement is when lying on a desk, undisturbed.

Covering the capacitor with tissue removes the fluctuations. De-soldering the capacitor gives a steady V_err with noise consistent with the unfiltered DAC. 

For the de-soldered capacitor:
RMS noise = 8.4 mV
200 kHz pole in V_offset addition
2000x gain to v_err
=> 9 nV/sqrt(Hz) noise
From DAC data-sheet: 11.8 nV/sqrt(Hz)

![Screenshot from 2019-10-28 18-51-24](https://user-images.githubusercontent.com/14295481/67708375-f9632f80-f9b3-11e9-89e9-1a4d8b063023.png)

**Comment by cjbe** [comment]
Good find! What is the plan to fix this - replace it with an electrolytic?

**Comment by pathfinder49** [comment]
The Previous measurement was with the board:
> 
> TS
> 270/19
> 002

Using another board:
> 
> TS
> 270/19
> 001

The behavior is NOT observed. The output is stable with 6 mV RMS noise. Touching the capacitor still causes causes large voltage spikes of over 1 V.

**Comment by pathfinder49** [comment]
> Good find! What is the plan to fix this - replace it with an electrolytic?

Seems to be the case of a broken capacitor?

**Comment by hartytp** [comment]
I don’t know what to do here. Let’s gather statistics with the other boards before making a decision. Maybe it was a broken cap (I don’t understand the physics behind such a large thermal emf otherwise)? 

With electros I’d worry about the leakage temp co as the dac has a high z output. Could consider reducing the cap size and going for a large plastic?

**Comment by dnadlinger** [comment]
We could always add a second buffer stage and use the leakage-free parallel RC technique (i.e. keep zero volts across one capacitor up to R matching, which can then be leaky).

**Comment by dnadlinger** [comment]
It really feels like this shouldn't be that big an effect, though.

**Comment by hartytp** [comment]
Let's assume it was a broken cap. We'll gather more statistics for looking at other boards, and only worry if the issue surfaces on a new board...
