### ISSUE TITLE
FEEDBACK_OFFSET transconductance gain annotation

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/stabilizer_current_sense#15]
According to the schematic, the transconductance from FEEDBACK_OFFSET to the feedback shunt current is 47 mA / V, but it looks like it should be 23.5 mA / V, giving a total range of 0 mA to 48 mA.

**Comment by dnadlinger** [comment]
I checked the rest of the gain calculations as well, and they are correct (divider ratios are slightly off).

**Comment by hartytp** [comment]
Thanks!

**Comment by hartytp** [comment]
I suspect I changed the sense resistor at some point and forgot to update the annotation.
